server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/handou?characterEncoding=utf-8
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  #心跳
    lease-expiration-duration-in-seconds: 15  #过期时间
mybatis:
  type-aliases-package: com.handou.item.pojo